<!-- START of: finna - Helpers/pagination-simple.phtml -->
<? if ($this->pageCount): ?>
  <ul class="paginationSimple">
    <li<? if (isset($this->previous)): ?>>
      <? $newParams = $this->params; $newParams['page'] = $this->previous; ?>
      <? if (isset($sort)): ?>
        <a href="<?= $this->currentPath() . '?' . http_build_query($newParams) . '&sort=' . $sort; ?>">
      <? else: ?>
        <a href="<?= $this->currentPath() . '?' . http_build_query($newParams); ?>">
      <? endif; ?>
      <span class="sr-only"><?=$this->transEsc('Previous Page')?></span><i class="fa fa-arrow-alt-left"></i>
      </a>
    <? endif; ?>
    </li>
    <li>
      <?=$this->label ?: $this->translate(
        'showing_results_of_html', [
          '%%start%%' => $this->firstItemNumber,
          '%%end%%' => $this->lastItemNumber,
          '%%total%%' => $this->localizedNumber($this->totalItemCount)
        ]
      );?>
    </li>
    <li<? if (isset($this->next)): ?>>
      <? $newParams = $this->params; $newParams['page'] = $this->next; ?>
      <? if (isset($sort)): ?>
        <a href="<?= $this->currentPath() . '?' . http_build_query($newParams) . '&sort=' . $sort; ?>">
      <? else: ?>
        <a href="<?= $this->currentPath() . '?' . http_build_query($newParams); ?>">
      <? endif; ?>
        <span class="sr-only"><?=$this->transEsc('Next Page')?></span><i class="fa fa-arrow-alt-right"></i>
      </a>
    <? endif; ?>
    </li>
  </ul>
<? endif; ?>
<!-- END of: finna - Helpers/pagination-simple.phtml -->
