<ul>
<? if ($this->phones['museum'] == false): ?>
  <? foreach ($this->phones as $phone): ?>
    <li><p><i class="fa fa-phone-square"></i><a href="tel:<?=$this->escapeHtmlAttr($phone['number'])?>"><?=$this->escapeHtml($phone['number'])?></a><?= isset($phone['name']) ? (' / ' . $this->escapeHtml($phone['name'])) : ''?></p></li>
  <? endforeach ?>
<? else: ?>
  <? foreach ($this->phones as $phone): ?>
    <li><p><a href="<?=$this->escapeHtmlAttr($phone['number'])?>"><?=$this->translate($phone['number'])?></a><?= isset($phone['name']) ? (' / ' . $this->escapeHtml($phone['name'])) : ''?></p></li><br/>
  <? endforeach ?>
<? endif; ?>
</ul>
