<? if ($this->pageCount): ?>
  <ul class="pagination">
    <? if (isset($this->previous)): ?>
      <? if (isset($sort)): ?>
        <? $newParams = $this->params; $newParams['page'] = 1; ?>
        <li class="pagination-button"><a href="<?=$this->currentPath() . '?' . http_build_query($newParams) . '&sort=' . $sort;?>"><i class="fa fa-first-page"></i><span class="sr-only"><?=$this->transEsc('First')?></span></a></li>
        <? $newParams = $this->params; $newParams['page'] = $this->previous; ?>
        <li class="pagination-button"><a href="<?=$this->currentPath() . '?' . http_build_query($newParams) . '&sort=' . $sort;?>"><i class="fa fa-arrow-alt-left"></i><span class="sr-only"><?=$this->transEsc('Prev')?></span></a></li>
      <? else: ?>
        <? $newParams = $this->params; $newParams['page'] = 1; ?>
        <li class="pagination-button"><a href="<?=$this->currentPath() . '?' . http_build_query($newParams)?>"><i class="fa fa-first-page"></i><span class="sr-only"><?=$this->transEsc('First')?></span></a></li>
        <? $newParams = $this->params; $newParams['page'] = $this->previous; ?>
        <li class="pagination-button"><a href="<?=$this->currentPath() . '?' . http_build_query($newParams)?>"><i class="fa fa-arrow-alt-left"></i><span class="sr-only"><?=$this->transEsc('Prev')?></span></a></li>
      <? endif; ?>
    <? endif; ?>
    <? if (count($this->pagesInRange) > 1): ?>
      <? foreach ($this->pagesInRange as $page): ?>
        <? if ($page != $this->current): ?>
          <? $newParams = $this->params; $newParams['page'] = $page; ?>
          <? if (isset($sort)): ?>
            <li><a href="<?=$this->currentPath() . '?' . http_build_query($newParams) . '&sort=' . $sort;?>"><?=$page?></a></li>
          <? else: ?>
            <li><a href="<?=$this->currentPath() . '?' . http_build_query($newParams)?>"><?=$page?></a></li>
          <? endif; ?>
        <? else: ?>
          <li class="active"><span><?=$page?></span></li>
        <? endif; ?>
      <? endforeach; ?>
    <? endif; ?>
    <? if (isset($this->next)): ?>
      <? if (isset($sort)): ?>
        <? $newParams = $this->params; $newParams['page'] = $this->next; ?>
        <li class="pagination-button"><a href="<?=$this->currentPath() . '?' . http_build_query($newParams) . '&sort=' . $sort;?>"><i class="fa fa-arrow-alt-right"></i><span class="sr-only"><?=$this->transEsc('Next');?></span></a></li>
        <? $newParams = $this->params; $newParams['page'] = $this->pageCount; ?>
        <li class="pagination-button"><a href="<?=$this->currentPath() . '?' . http_build_query($newParams) . '&sort=' . $sort;?>"><i class="fa fa-last-page"></i><span class="sr-only"><?=$this->transEsc('Last')?></span></a></li>
      <? else: ?>
        <? $newParams = $this->params; $newParams['page'] = $this->next; ?>
        <li class="pagination-button"><a href="<?=$this->currentPath() . '?' . http_build_query($newParams)?>"><i class="fa fa-arrow-alt-right"></i><span class="sr-only"><?=$this->transEsc('Next');?></span></a></li>
        <? $newParams = $this->params; $newParams['page'] = $this->pageCount; ?>
        <li class="pagination-button"><a href="<?=$this->currentPath() . '?' . http_build_query($newParams)?>"><i class="fa fa-last-page"></i><span class="sr-only"><?=$this->transEsc('Last')?></span></a></li>
      <? endif; ?>
    <? endif; ?>
  </ul>
<? endif; ?>
