<!-- START of: finna - RecordDriver/MetaLib/list-entry.phtml -->
<?
  // Set up some convenience variables:
  $id = $this->driver->getUniqueId();
  $source = $this->driver->getSourceIdentifier();
  if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->id;
    $user_id = $this->list->user_id;
  } else {
    $list_id = null;
    $user_id = $this->user ? $this->user->id : null;
  }
error_log("list: $list_id");
?>
<!-- start list-entry -->
<div class="row record-container myresearch-row">
  <div class="col-xs-2 col-sm-1 hidden-print">
    <div class="checkboxFilter">
      <div class="checkbox">
        <? // Request a checkbox with a label (can't add the label here as checkbox template contains more than one field): ?>
        <?=$this->record($this->driver)->getCheckbox('', true) ?>
      </div>
    </div>
    <input type="hidden" value="<?=$this->escapeHtmlAttr("MetaLib.$id") ?>" class="hiddenId"/>
  </div>
  <div class="col-xs-2 col-sm-2 text-center"></div>
  <div class="col-xs-8 col-sm-9">
    <div class="resultItemLine1"><h3><?=$this->driver->getTitle()?></h3></div>
    <? if ($author = $this->driver->getPrimaryAuthor()): ?>    
    <div class="record-authors"><?=$author?></div>
    <? endif; ?>
    <? if ($year = $this->driver->getPublicationDates()): ?>    
    <div class="record-year"><?=$year?></div>
    <? endif; ?>
    <div class="last"></div>
    <div class="myresearch-notes">

      <?
      $hasNote = false;
      $notes = false;
      $listNotes = $list_id != null ? $this->driver->getListNotes($list_id, $user_id) : false;
      if ($listNotes) {
        $notes = implode('', $listNotes);
        $notes = preg_replace("/\r\n|\r|\n/",'<br class="newline">', $this->escapeHtml($notes));
        $hasNote = strlen($notes) > 0;
      }
    ?>
      <div class="note-info <?= $hasNote ? '' : ' hide' ?>"><strong><?=$this->transEsc('Description')?>:</strong></div>
      <div><?= $notes; ?></div>
    </div>
  </div>
</div>
<!-- END of: finna - RecordDriver/MetaLib/list-entry.phtml -->
